#!/usr/bin/env python

import struct
import sys
import os
import threading
import Queue

fifo = "/tmp/xmobar-hipchat"

# Thread that reads messages from the webapp.
def read_thread_func(queue):
    message_number = 0
    while True:
        text_length_bytes = sys.stdin.read(4)
        if len(text_length_bytes) == 0:
            queue.put(None)
        text_length = struct.unpack('i', text_length_bytes)[0]
        text = sys.stdin.read(text_length).decode('utf-8')
        if len(text) > 2:
            text = text[1:-1]
        queue.put(text)

def listen(queue):
    try:
        with open(fifo, "w") as f:
            while True:
                line = queue.get()
                if line is None:
                    break
                f.write(line + "\n")
                f.flush()
    except IOError as err:
        return err
    return None

def main():
    queue = Queue.Queue()
    thread = threading.Thread(target=read_thread_func, args=(queue,))
    thread.daemon = True
    thread.start()
    if not os.path.exists(fifo):
        os.mkfifo(fifo)
    while True:
        a = listen(queue)
        if a is None:
            break
        print a
    sys.exit(0)

if __name__ == '__main__':
    main()
