#!/usr/bin/env python

import struct
import sys
import threading
import Queue

# Thread that reads messages from the webapp.
def read_thread_func(queue):
    message_number = 0
    while True:
        text_length_bytes = sys.stdin.read(4)
        if len(text_length_bytes) == 0:
            queue.put(None)
        text_length = struct.unpack('i', text_length_bytes)[0]
        text = sys.stdin.read(text_length).decode('utf-8')
        if len(text) > 2:
            text = text[1:-1]
        queue.put(text)

def main():
    queue = Queue.Queue()
    thread = threading.Thread(target=read_thread_func, args=(queue,))
    thread.daemon = True
    thread.start()
    while True:
        try:
            with open("/tmp/xmobar-hipchat", "w") as f:
                while True:
                    line = queue.get()
                    if line is None:
                        break
                    f.write(line + "\n")
                    f.flush()
        except IOError as err:
            print err
    sys.exit(0)

if __name__ == '__main__':
    main()
